name: Main workflow
on: [push]
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
      
    - name: Install package dependencies 
      run: yarn --cwd typescript

    - name: Fix Package to ensure there were no errors
      run: yarn --cwd typescript fix

  publish-typescript:
    if: github.ref == 'refs/heads/main'
    name: Publish Typescript Library
    runs-on: ubuntu-latest
    needs: build

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        registry-url: 'https://npm.pkg.github.com'
    
    - name: Install package dependencies
      run: yarn --cwd typescript

    - name: Fix Package to ensure there were no errors
      run: yarn --cwd typescript fix

    - name: Publish package
      run: yarn --cwd typescript publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

